### ISSUE TITLE
TODO 3: Final Release

### ISSUE THREAD

**Issue by stefan2904** [stefan2904/bakk-thesis#2]
* [x] clean repository
* [x] create final pdf
* [ ] sign final pdf
* [x] publish & release/tag signed final pdf 
* [ ] [Get DOI](https://zenodo.org/account/settings/github/)
* [x] name enlargement certificate
