### ISSUE TITLE
TODO 1: Final text, Formalities, Copy editing

### ISSUE THREAD

**Issue by stefan2904** [stefan2904/bakk-thesis#3]
* [x] Write
* [x] Write more
* [x] Structure
* [x] Write even more
* [x] Restructure
* [x] Create plots
* [x] LaTeX'ify everything
* [x] Write another time
* [ ] ~~Add attacks?~~
* [x] Revise current text
* [x] Add last plots
* [x] Check integrity and structure (on paper!)
* [x] Add references
* [x] Finalize Preliminaries
* [x] Finalize Introduction
* [x] Add references
* [x] Copy editing
* [x] Write Abstract
* [x] More copy editing
* [ ] check checklist.txt
* [x] grammar
* [x] references
